SELECT f.FLAVOR
FROM FIRST_HALF AS f
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS july_total
    FROM JULY
    GROUP BY FLAVOR
) AS j
ON f.FLAVOR = j.FLAVOR
ORDER BY (f.TOTAL_ORDER + j.july_total) DESC
LIMIT 3;